//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaceRored.ServiceReferenceRobert {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Data_WCF_Limits", Namespace="http://schemas.datacontract.org/2004/07/Robert_KC11")]
    [System.SerializableAttribute()]
    public partial class Data_WCF_Limits : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float diameter_maxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float diameter_minField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float ovality_maxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float straightness_maxField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float diameter_max {
            get {
                return this.diameter_maxField;
            }
            set {
                if ((this.diameter_maxField.Equals(value) != true)) {
                    this.diameter_maxField = value;
                    this.RaisePropertyChanged("diameter_max");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float diameter_min {
            get {
                return this.diameter_minField;
            }
            set {
                if ((this.diameter_minField.Equals(value) != true)) {
                    this.diameter_minField = value;
                    this.RaisePropertyChanged("diameter_min");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float ovality_max {
            get {
                return this.ovality_maxField;
            }
            set {
                if ((this.ovality_maxField.Equals(value) != true)) {
                    this.ovality_maxField = value;
                    this.RaisePropertyChanged("ovality_max");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float straightness_max {
            get {
                return this.straightness_maxField;
            }
            set {
                if ((this.straightness_maxField.Equals(value) != true)) {
                    this.straightness_maxField = value;
                    this.RaisePropertyChanged("straightness_max");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sum_WCF_Data", Namespace="http://schemas.datacontract.org/2004/07/Robert_KC11")]
    [System.SerializableAttribute()]
    public partial class Sum_WCF_Data : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FaceRored.ServiceReferenceRobert.State_Communication_Anybus scaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FaceRored.ServiceReferenceRobert.State_Communication_Zumbach sczField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FaceRored.ServiceReferenceRobert.Data_WCF_Result wcf_measure_autoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FaceRored.ServiceReferenceRobert.Data_WCF_Result wcf_measure_clientField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FaceRored.ServiceReferenceRobert.State_Communication_Anybus sca {
            get {
                return this.scaField;
            }
            set {
                if ((object.ReferenceEquals(this.scaField, value) != true)) {
                    this.scaField = value;
                    this.RaisePropertyChanged("sca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FaceRored.ServiceReferenceRobert.State_Communication_Zumbach scz {
            get {
                return this.sczField;
            }
            set {
                if ((object.ReferenceEquals(this.sczField, value) != true)) {
                    this.sczField = value;
                    this.RaisePropertyChanged("scz");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FaceRored.ServiceReferenceRobert.Data_WCF_Result wcf_measure_auto {
            get {
                return this.wcf_measure_autoField;
            }
            set {
                if ((object.ReferenceEquals(this.wcf_measure_autoField, value) != true)) {
                    this.wcf_measure_autoField = value;
                    this.RaisePropertyChanged("wcf_measure_auto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FaceRored.ServiceReferenceRobert.Data_WCF_Result wcf_measure_client {
            get {
                return this.wcf_measure_clientField;
            }
            set {
                if ((object.ReferenceEquals(this.wcf_measure_clientField, value) != true)) {
                    this.wcf_measure_clientField = value;
                    this.RaisePropertyChanged("wcf_measure_client");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="State_Communication_Anybus", Namespace="http://schemas.datacontract.org/2004/07/Robert_KC11")]
    [System.SerializableAttribute()]
    public partial class State_Communication_Anybus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool is_alive_plcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool is_exists_communicationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool is_good_dataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool is_open_portField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool is_alive_plc {
            get {
                return this.is_alive_plcField;
            }
            set {
                if ((this.is_alive_plcField.Equals(value) != true)) {
                    this.is_alive_plcField = value;
                    this.RaisePropertyChanged("is_alive_plc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool is_exists_communication {
            get {
                return this.is_exists_communicationField;
            }
            set {
                if ((this.is_exists_communicationField.Equals(value) != true)) {
                    this.is_exists_communicationField = value;
                    this.RaisePropertyChanged("is_exists_communication");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool is_good_data {
            get {
                return this.is_good_dataField;
            }
            set {
                if ((this.is_good_dataField.Equals(value) != true)) {
                    this.is_good_dataField = value;
                    this.RaisePropertyChanged("is_good_data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool is_open_port {
            get {
                return this.is_open_portField;
            }
            set {
                if ((this.is_open_portField.Equals(value) != true)) {
                    this.is_open_portField = value;
                    this.RaisePropertyChanged("is_open_port");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="State_Communication_Zumbach", Namespace="http://schemas.datacontract.org/2004/07/Robert_KC11")]
    [System.SerializableAttribute()]
    public partial class State_Communication_Zumbach : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool is_exists_communicationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool is_good_dataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool is_open_portField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool is_exists_communication {
            get {
                return this.is_exists_communicationField;
            }
            set {
                if ((this.is_exists_communicationField.Equals(value) != true)) {
                    this.is_exists_communicationField = value;
                    this.RaisePropertyChanged("is_exists_communication");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool is_good_data {
            get {
                return this.is_good_dataField;
            }
            set {
                if ((this.is_good_dataField.Equals(value) != true)) {
                    this.is_good_dataField = value;
                    this.RaisePropertyChanged("is_good_data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool is_open_port {
            get {
                return this.is_open_portField;
            }
            set {
                if ((this.is_open_portField.Equals(value) != true)) {
                    this.is_open_portField = value;
                    this.RaisePropertyChanged("is_open_port");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Data_WCF_Result", Namespace="http://schemas.datacontract.org/2004/07/Robert_KC11")]
    [System.SerializableAttribute()]
    public partial class Data_WCF_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FaceRored.ServiceReferenceRobert.Data_WCF_Calculate_Measure data_wcf_calculate_measureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FaceRored.ServiceReferenceRobert.Data_WCF_Limits data_wcf_limitsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FaceRored.ServiceReferenceRobert.Data_WCF_Material data_wcf_materialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FaceRored.ServiceReferenceRobert.Data_WCF_Measure data_wcf_measureField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FaceRored.ServiceReferenceRobert.Data_WCF_Calculate_Measure data_wcf_calculate_measure {
            get {
                return this.data_wcf_calculate_measureField;
            }
            set {
                if ((object.ReferenceEquals(this.data_wcf_calculate_measureField, value) != true)) {
                    this.data_wcf_calculate_measureField = value;
                    this.RaisePropertyChanged("data_wcf_calculate_measure");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FaceRored.ServiceReferenceRobert.Data_WCF_Limits data_wcf_limits {
            get {
                return this.data_wcf_limitsField;
            }
            set {
                if ((object.ReferenceEquals(this.data_wcf_limitsField, value) != true)) {
                    this.data_wcf_limitsField = value;
                    this.RaisePropertyChanged("data_wcf_limits");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FaceRored.ServiceReferenceRobert.Data_WCF_Material data_wcf_material {
            get {
                return this.data_wcf_materialField;
            }
            set {
                if ((object.ReferenceEquals(this.data_wcf_materialField, value) != true)) {
                    this.data_wcf_materialField = value;
                    this.RaisePropertyChanged("data_wcf_material");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FaceRored.ServiceReferenceRobert.Data_WCF_Measure data_wcf_measure {
            get {
                return this.data_wcf_measureField;
            }
            set {
                if ((object.ReferenceEquals(this.data_wcf_measureField, value) != true)) {
                    this.data_wcf_measureField = value;
                    this.RaisePropertyChanged("data_wcf_measure");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Data_WCF_Calculate_Measure", Namespace="http://schemas.datacontract.org/2004/07/Robert_KC11")]
    [System.SerializableAttribute()]
    public partial class Data_WCF_Calculate_Measure : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int count_measure_deviationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int count_measure_diameterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float deviation_maxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float deviation_minField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float diameter_maxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float diameter_minField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool is_bad_measureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool is_good_diameterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool is_good_ovalityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool is_good_straightnessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float ovality_maxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float straightness_maxField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int count_measure_deviation {
            get {
                return this.count_measure_deviationField;
            }
            set {
                if ((this.count_measure_deviationField.Equals(value) != true)) {
                    this.count_measure_deviationField = value;
                    this.RaisePropertyChanged("count_measure_deviation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int count_measure_diameter {
            get {
                return this.count_measure_diameterField;
            }
            set {
                if ((this.count_measure_diameterField.Equals(value) != true)) {
                    this.count_measure_diameterField = value;
                    this.RaisePropertyChanged("count_measure_diameter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float deviation_max {
            get {
                return this.deviation_maxField;
            }
            set {
                if ((this.deviation_maxField.Equals(value) != true)) {
                    this.deviation_maxField = value;
                    this.RaisePropertyChanged("deviation_max");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float deviation_min {
            get {
                return this.deviation_minField;
            }
            set {
                if ((this.deviation_minField.Equals(value) != true)) {
                    this.deviation_minField = value;
                    this.RaisePropertyChanged("deviation_min");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float diameter_max {
            get {
                return this.diameter_maxField;
            }
            set {
                if ((this.diameter_maxField.Equals(value) != true)) {
                    this.diameter_maxField = value;
                    this.RaisePropertyChanged("diameter_max");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float diameter_min {
            get {
                return this.diameter_minField;
            }
            set {
                if ((this.diameter_minField.Equals(value) != true)) {
                    this.diameter_minField = value;
                    this.RaisePropertyChanged("diameter_min");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool is_bad_measure {
            get {
                return this.is_bad_measureField;
            }
            set {
                if ((this.is_bad_measureField.Equals(value) != true)) {
                    this.is_bad_measureField = value;
                    this.RaisePropertyChanged("is_bad_measure");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool is_good_diameter {
            get {
                return this.is_good_diameterField;
            }
            set {
                if ((this.is_good_diameterField.Equals(value) != true)) {
                    this.is_good_diameterField = value;
                    this.RaisePropertyChanged("is_good_diameter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool is_good_ovality {
            get {
                return this.is_good_ovalityField;
            }
            set {
                if ((this.is_good_ovalityField.Equals(value) != true)) {
                    this.is_good_ovalityField = value;
                    this.RaisePropertyChanged("is_good_ovality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool is_good_straightness {
            get {
                return this.is_good_straightnessField;
            }
            set {
                if ((this.is_good_straightnessField.Equals(value) != true)) {
                    this.is_good_straightnessField = value;
                    this.RaisePropertyChanged("is_good_straightness");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float ovality_max {
            get {
                return this.ovality_maxField;
            }
            set {
                if ((this.ovality_maxField.Equals(value) != true)) {
                    this.ovality_maxField = value;
                    this.RaisePropertyChanged("ovality_max");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float straightness_max {
            get {
                return this.straightness_maxField;
            }
            set {
                if ((this.straightness_maxField.Equals(value) != true)) {
                    this.straightness_maxField = value;
                    this.RaisePropertyChanged("straightness_max");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Data_WCF_Material", Namespace="http://schemas.datacontract.org/2004/07/Robert_KC11")]
    [System.SerializableAttribute()]
    public partial class Data_WCF_Material : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint number_jobField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint number_programField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint number_semiproductField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint number_job {
            get {
                return this.number_jobField;
            }
            set {
                if ((this.number_jobField.Equals(value) != true)) {
                    this.number_jobField = value;
                    this.RaisePropertyChanged("number_job");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint number_program {
            get {
                return this.number_programField;
            }
            set {
                if ((this.number_programField.Equals(value) != true)) {
                    this.number_programField = value;
                    this.RaisePropertyChanged("number_program");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint number_semiproduct {
            get {
                return this.number_semiproductField;
            }
            set {
                if ((this.number_semiproductField.Equals(value) != true)) {
                    this.number_semiproductField = value;
                    this.RaisePropertyChanged("number_semiproduct");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Data_WCF_Measure", Namespace="http://schemas.datacontract.org/2004/07/Robert_KC11")]
    [System.SerializableAttribute()]
    public partial class Data_WCF_Measure : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float deviationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float diameterField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float deviation {
            get {
                return this.deviationField;
            }
            set {
                if ((this.deviationField.Equals(value) != true)) {
                    this.deviationField = value;
                    this.RaisePropertyChanged("deviation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float diameter {
            get {
                return this.diameterField;
            }
            set {
                if ((this.diameterField.Equals(value) != true)) {
                    this.diameterField = value;
                    this.RaisePropertyChanged("diameter");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceRobert.I_WCF_Contract", CallbackContract=typeof(FaceRored.ServiceReferenceRobert.I_WCF_ContractCallback))]
    public interface I_WCF_Contract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_WCF_Contract/Connect", ReplyAction="http://tempuri.org/I_WCF_Contract/ConnectResponse")]
        void Connect();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_WCF_Contract/Disconnect", ReplyAction="http://tempuri.org/I_WCF_Contract/DisconnectResponse")]
        void Disconnect();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/I_WCF_Contract/StartMeasure")]
        void StartMeasure();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/I_WCF_Contract/Set_Limits")]
        void Set_Limits(FaceRored.ServiceReferenceRobert.Data_WCF_Limits data_wcf_limits);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_WCF_Contract/ReadResFile", ReplyAction="http://tempuri.org/I_WCF_Contract/ReadResFileResponse")]
        System.Data.DataTable ReadResFile(System.DateTime dt_res_file);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface I_WCF_ContractCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/I_WCF_Contract/Set_Client_State_And_Measure")]
        void Set_Client_State_And_Measure(FaceRored.ServiceReferenceRobert.Sum_WCF_Data sum_wcf_data);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/I_WCF_Contract/Set_Client_Measure_Complete")]
        void Set_Client_Measure_Complete(FaceRored.ServiceReferenceRobert.Data_WCF_Result wcf_measure);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/I_WCF_Contract/Set_Auto_Measure_Complete")]
        void Set_Auto_Measure_Complete(FaceRored.ServiceReferenceRobert.Data_WCF_Result wcf_measure);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface I_WCF_ContractChannel : FaceRored.ServiceReferenceRobert.I_WCF_Contract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class I_WCF_ContractClient : System.ServiceModel.DuplexClientBase<FaceRored.ServiceReferenceRobert.I_WCF_Contract>, FaceRored.ServiceReferenceRobert.I_WCF_Contract {
        
        public I_WCF_ContractClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public I_WCF_ContractClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public I_WCF_ContractClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public I_WCF_ContractClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public I_WCF_ContractClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Connect() {
            base.Channel.Connect();
        }
        
        public void Disconnect() {
            base.Channel.Disconnect();
        }
        
        public void StartMeasure() {
            base.Channel.StartMeasure();
        }
        
        public void Set_Limits(FaceRored.ServiceReferenceRobert.Data_WCF_Limits data_wcf_limits) {
            base.Channel.Set_Limits(data_wcf_limits);
        }
        
        public System.Data.DataTable ReadResFile(System.DateTime dt_res_file) {
            return base.Channel.ReadResFile(dt_res_file);
        }
    }
}
